<x-layouts.app title="Setup">
    <header class="border-b border-slate-800 pb-7"><p class="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-400">Welcome, {{ auth()->user()->name }}</p><h1 class="mt-2 text-3xl font-semibold text-white">Set up your trading workspace</h1><p class="mt-2 text-sm text-slate-400">Your account starts in safe PAPER + SIGNAL mode.</p></header>
    @if(session('success'))<div class="rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-4 text-sm text-emerald-200">{{ session('success') }}</div>@endif
    <section class="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]">
        <div class="rounded-2xl border border-slate-800 bg-slate-900/70 p-6">
            <h2 class="text-xl font-semibold text-white">Setup progress</h2>
            <div class="mt-5 space-y-3">
                @foreach(['account' => 'Account created', 'email' => 'Verify email', 'paper_account' => 'Paper account ready', 'telegram_bot' => 'Connect Telegram bot', 'telegram_link' => 'Link Telegram account', 'preferences' => 'Review trading mode', 'strategy' => 'Review strategy'] as $key => $label)
                    <div class="flex items-center gap-3 rounded-xl border border-slate-800 bg-slate-950/50 px-4 py-3"><span class="flex size-6 items-center justify-center rounded-full {{ $status[$key] ? 'bg-emerald-400 text-slate-950' : 'bg-slate-800 text-slate-400' }}">{{ $status[$key] ? '✓' : '○' }}</span><span class="text-sm {{ $status[$key] ? 'text-slate-200' : 'text-slate-400' }}">{{ $label }}</span></div>
                @endforeach
            </div>
        </div>
        <div class="space-y-6">
            @unless($status['email'])<article class="rounded-2xl border border-amber-400/20 bg-amber-400/5 p-6"><h2 class="font-semibold text-amber-200">Verify your email</h2><p class="mt-2 text-sm text-slate-400">Verification unlocks Telegram setup, scans, approvals, and AUTO mode.</p><a href="{{ route('verification.notice') }}" class="mt-4 inline-block rounded-xl bg-amber-300 px-4 py-2.5 text-sm font-semibold text-slate-950">Verify Email</a></article>@endunless
            <article class="rounded-2xl border border-sky-400/20 bg-slate-900/70 p-6"><h2 class="text-xl font-semibold text-white">Connect your Telegram bot</h2><ol class="mt-4 list-decimal space-y-2 pl-5 text-sm text-slate-300"><li>Open Telegram and search for @BotFather.</li><li>Send /newbot.</li><li>Follow BotFather's instructions.</li><li>Copy the bot token.</li><li>Return here and paste the token and bot username.</li><li>Connect the bot; its webhook is configured automatically.</li><li>Link your personal Telegram account.</li></ol><a href="{{ route('telegram.settings') }}" class="mt-5 inline-block rounded-xl bg-sky-400 px-4 py-2.5 text-sm font-semibold text-slate-950">{{ $status['telegram_bot'] ? 'Manage Telegram' : 'Connect Telegram' }}</a></article>
            <article class="rounded-2xl border border-violet-400/20 bg-slate-900/70 p-6"><h2 class="text-xl font-semibold text-white">Trading mode</h2><p class="mt-2 text-sm text-slate-400"><strong class="text-white">SIGNAL</strong> alerts only. <strong class="text-white">CONFIRM</strong> waits for approval. <strong class="text-white">AUTO</strong> can open qualified PAPER positions automatically—never live trades.</p><p class="mt-3 text-sm text-violet-300">Current: PAPER + {{ strtoupper($preference->entry_mode->value) }}</p><a href="{{ route('dashboard') }}#trading-preferences" class="mt-4 inline-block text-sm font-semibold text-violet-300">Review trading mode →</a></article>
            <article class="rounded-2xl border border-emerald-400/20 bg-slate-900/70 p-6"><h2 class="text-xl font-semibold text-white">Paper strategy</h2><p class="mt-2 text-sm text-slate-300">SL -{{ $strategy['stop_loss_percent'] }}% · P1 +{{ $strategy['protection_level_1_percent'] }}% · P2 +{{ $strategy['protection_level_2_percent'] }}%</p><p class="mt-2 text-xs text-slate-500">Changes apply to new positions; existing positions keep their snapshot.</p><a href="{{ route('dashboard') }}#paper-strategy" class="mt-4 inline-block text-sm font-semibold text-emerald-300">Review strategy →</a></article>
            @if($status['ready'])<form method="POST" action="{{ route('dashboard.actions.store', 'token-scan') }}" class="rounded-2xl border border-emerald-400/30 bg-emerald-400/5 p-6">@csrf<input type="hidden" name="chain" value="solana"><h2 class="text-xl font-semibold text-emerald-200">Your workspace is ready</h2><p class="mt-2 text-sm text-slate-400">Run a user-scoped Solana scan using your current PAPER entry mode.</p><button class="mt-4 rounded-xl bg-emerald-400 px-5 py-3 font-semibold text-slate-950">Run My First Scan</button></form>@endif
        </div>
    </section>
</x-layouts.app>
