<x-layouts.admin title="Admin Dashboard">
    <header class="flex flex-col gap-5 border-b border-slate-800/80 pb-7 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-sm font-bold uppercase tracking-[0.2em] text-blue-400">Admin dashboard</p><h1 class="mt-2 text-4xl font-bold tracking-tight text-white lg:text-5xl">Welcome back, {{ auth()->user()->name }}</h1><p class="mt-3 max-w-3xl text-base leading-7 text-slate-400 lg:text-lg">Monitor system health, trading activity, users, and platform operations.</p></div><div class="rounded-2xl border border-slate-800 bg-slate-900/60 p-2"><x-admin.status-badge :status="$operationalStatus['failed_jobs'] > 0 ? 'critical' : ($operationalStatus['scheduler']['status'] === 'healthy' ? 'healthy' : 'stale')" /></div></header>

    @php
        $flashClasses = [
            'success' => 'border-emerald-400/20 bg-emerald-400/10 text-emerald-200',
            'warning' => 'border-amber-400/20 bg-amber-400/10 text-amber-200',
            'error' => 'border-red-400/20 bg-red-400/10 text-red-200',
        ];
    @endphp
    @foreach($flashClasses as $flash => $classes)
        @if(session($flash))
            <div class="rounded-xl border px-4 py-3 text-sm {{ $classes }}">{{ session($flash) }}</div>
        @endif
    @endforeach
    @if($errors->any())<div class="rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200">{{ $errors->first() }}</div>@endif

    <section class="grid gap-5 sm:grid-cols-2 2xl:grid-cols-4" aria-label="Platform summary">
        <x-admin.stat-card label="Total Users" :value="number_format($adminOverview['users'])" detail="Registered platform accounts" tone="blue" icon="♟" />
        <x-admin.stat-card label="Opportunities" :value="number_format($adminOverview['opportunities'])" :detail="$opportunitySummary['recent'].' in 24h · '.$opportunitySummary['pending'].' pending confirmation'" tone="violet" icon="◇" />
        <x-admin.stat-card label="Open Paper Positions" :value="number_format($adminOverview['open_positions'])" detail="Funded positions across the platform" tone="emerald" icon="↗" />
        <x-admin.stat-card label="Failed Jobs" :value="number_format($operationalStatus['failed_jobs'])" :detail="number_format($operationalStatus['pending_jobs']).' jobs currently pending'" :tone="$operationalStatus['failed_jobs'] > 0 ? 'red' : 'amber'" icon="!" />
    </section>

    <div class="grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_minmax(360px,0.8fr)]">
        <x-admin.panel id="scanner-controls" title="Quick Actions" eyebrow="Operations">
            <div class="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p class="text-base text-slate-400">Run existing queue-backed administrative commands.</p><label class="flex items-center gap-2.5 text-sm font-medium text-slate-400">Chain<select id="scanner-chain" class="rounded-xl border border-slate-700 bg-slate-950 px-3.5 py-2.5 text-sm text-slate-200"><option value="solana">Solana</option><option value="ethereum">Ethereum</option></select></label></div>
            <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">@foreach($dashboardActions as $action => $definition)<form method="POST" action="{{ route('dashboard.actions.store', $action) }}" class="dashboard-action-form" data-action="{{ $action }}" data-action-key="{{ in_array($action, ['token-scan', 'momentum-scan']) ? $action.':solana' : $action }}" @if(in_array($action, ['token-scan', 'momentum-scan'])) data-chain-action @endif>@csrf @if(in_array($action, ['token-scan', 'momentum-scan']))<input type="hidden" name="chain" value="solana" data-chain-input>@endif<button class="flex min-h-20 w-full items-center justify-between gap-3 rounded-xl border border-slate-800 bg-slate-950/60 p-4 text-left transition hover:border-blue-400/40 hover:bg-slate-900 disabled:opacity-50"><span><strong class="block text-[15px] text-white">{{ $definition['label'] }}</strong><span class="mt-1 block text-sm text-slate-500">Queue secure operation</span></span><span class="action-state text-sm font-bold uppercase tracking-wider text-blue-300">Run</span></button></form>@endforeach</div>
        </x-admin.panel>

        <x-admin.panel id="system-status" title="Background Process Health" eyebrow="System status">
            <div class="space-y-4">@foreach(['scheduler' => 'Scheduler', 'queue' => 'Queue Worker', 'fast_tracker' => 'Position Tracker'] as $key => $label)<div class="flex items-center justify-between gap-4 rounded-xl bg-slate-950/45 px-4 py-3"><div><p class="text-base font-medium text-slate-200">{{ $label }}</p><p class="mt-1 text-sm text-slate-500">{{ $operationalStatus[$key]['last_run_at']?->diffForHumans() ?? 'No heartbeat recorded' }}</p></div><x-admin.status-badge :status="$operationalStatus[$key]['status']" /></div>@endforeach<div class="flex items-center justify-between border-t border-slate-800 pt-4"><span class="text-base text-slate-300">Telegram Bots</span><span class="text-base font-semibold text-emerald-300">{{ $adminOverview['connected_bots'] }} connected</span></div><div class="flex items-center justify-between"><span class="text-base text-slate-300">Pending / Failed Jobs</span><span class="text-base font-semibold {{ $operationalStatus['failed_jobs'] > 0 ? 'text-red-300' : 'text-slate-300' }}">{{ $operationalStatus['pending_jobs'] }} / {{ $operationalStatus['failed_jobs'] }}</span></div></div>
        </x-admin.panel>
    </div>

    <section id="wallets" class="grid gap-6 xl:grid-cols-2">
        <x-admin.panel title="Admin Personal Paper Wallets" eyebrow="Isolated portfolio"><div class="grid gap-4 sm:grid-cols-2">@foreach($wallets as $wallet)<article class="rounded-2xl border border-slate-700/70 bg-gradient-to-br from-slate-950/80 to-slate-900 p-5"><div class="flex items-center justify-between"><strong class="text-lg text-white">{{ $wallet->chain->label() }}</strong><span class="rounded-lg border border-blue-400/20 bg-blue-400/10 px-2.5 py-1 text-sm font-semibold text-blue-300">{{ $wallet->currencyCode() }}</span></div><dl class="mt-5 grid grid-cols-2 gap-4"><div><dt class="text-sm text-slate-500">Available</dt><dd class="mt-1 text-xl font-bold text-emerald-300">{{ number_format($wallet->available_balance_sol, 4) }} {{ $wallet->currencyCode() }}</dd></div><div><dt class="text-sm text-slate-500">Invested</dt><dd class="mt-1 text-xl font-bold text-amber-300">{{ number_format($wallet->invested_balance_sol, 4) }} {{ $wallet->currencyCode() }}</dd></div></dl></article>@endforeach</div></x-admin.panel>
        <x-admin.panel title="Legacy Admin Ledgers" eyebrow="Null-owned historical data">@if($legacyWallets->isEmpty())<p class="rounded-xl border border-dashed border-amber-400/20 bg-amber-400/5 p-5 text-center text-base text-slate-400">No legacy wallet ledgers.</p>@else<div class="grid gap-4 sm:grid-cols-2">@foreach($legacyWallets as $wallet)<article class="rounded-2xl border border-amber-400/20 bg-gradient-to-br from-amber-400/10 to-slate-950/60 p-5"><div class="flex items-center justify-between"><strong class="text-lg text-white">{{ $wallet->chain->label() }}</strong><span class="rounded-lg border border-amber-400/20 bg-amber-400/10 px-2.5 py-1 text-sm font-semibold text-amber-300">LEGACY</span></div><p class="mt-5 text-2xl font-bold text-white">{{ number_format($wallet->available_balance_sol, 4) }} {{ $wallet->currencyCode() }}</p><p class="mt-2 text-sm text-slate-400">Invested <strong class="text-amber-300">{{ number_format($wallet->invested_balance_sol, 4) }} {{ $wallet->currencyCode() }}</strong></p></article>@endforeach</div>@endif</x-admin.panel>
    </section>

    <div id="admin-activity-endpoint" class="hidden" data-status-url="{{ route('dashboard.activity') }}"></div>
    <div class="grid items-start gap-6 xl:grid-cols-[minmax(0,1.15fr)_minmax(420px,0.85fr)]">
        <x-admin.panel id="positions" title="Open Positions" eyebrow="Admin and legacy" :action="route('trades.index')">
            @if($positions->isEmpty())
                <div class="flex items-center gap-4 rounded-xl border border-dashed border-slate-700 bg-slate-950/40 px-5 py-5"><span class="flex size-11 shrink-0 items-center justify-center rounded-xl bg-slate-800 text-xl text-slate-400">◎</span><div><p class="text-base font-semibold text-slate-200">No open positions</p><p class="mt-1 text-sm text-slate-500">New funded admin or legacy paper positions will appear here.</p></div></div>
            @else
                <div class="overflow-x-auto"><table class="w-full min-w-[720px] text-left text-[15px]"><thead class="text-sm text-slate-500"><tr><th class="pb-3 font-semibold">Token</th><th class="pb-3 font-semibold">Chain</th><th class="pb-3 font-semibold">Entry MC</th><th class="pb-3 font-semibold">Current</th><th class="pb-3 font-semibold">P/L</th><th class="pb-3 text-right font-semibold">Action</th></tr></thead><tbody class="divide-y divide-slate-800">@foreach($positions as $trade)@php($position = $trade['model'])<tr><td class="py-4"><strong class="text-base text-white">{{ $position->symbol }}</strong><span class="block max-w-52 truncate text-sm text-slate-500">{{ $position->address }}</span><span class="mt-1.5 block text-xs font-medium text-slate-400">Position strategy snapshot</span><span class="block text-xs text-slate-500">SL -{{ number_format($trade['strategy']['stop_loss_percent'], 2) }}% · P1 +{{ number_format($trade['strategy']['protection_level_1_percent'], 2) }}% · P2 +{{ number_format($trade['strategy']['protection_level_2_percent'], 2) }}%</span></td><td class="py-4 text-slate-300">{{ $position->chain->label() }}</td><td class="py-4 text-slate-300">${{ number_format($trade['entry_market_cap']) }}</td><td class="py-4 text-slate-300">${{ number_format($trade['current_market_cap']) }}</td><td class="py-4 font-semibold {{ $trade['unrealized_pnl'] >= 0 ? 'text-emerald-300' : 'text-red-300' }}">{{ $trade['unrealized_pnl'] >= 0 ? '+' : '' }}{{ number_format($trade['unrealized_pnl'], 4) }} {{ $trade['currency'] }}</td><td class="py-4 text-right"><button type="button" class="open-close-modal rounded-xl border border-red-400/25 bg-red-400/5 px-3.5 py-2.5 text-sm font-semibold text-red-300 transition hover:bg-red-400/10" data-action="{{ route('paper-trades.close', $position) }}" data-symbol="{{ $position->symbol }}" data-return="{{ number_format($trade['current_return'], 2) }}%" data-remaining="{{ number_format($trade['remaining_fraction'] * 100, 2) }}%" data-value="{{ number_format($trade['current_value'], 4) }} {{ $trade['currency'] }}">Close</button></td></tr>@endforeach</tbody></table></div>
            @endif
        </x-admin.panel>
        <x-admin.panel id="system-activity" title="Recent Activity" eyebrow="Commands"><div id="current-activity-empty" class="hidden"></div><div id="current-activity-content" class="hidden"><span id="current-activity-label"></span><span id="current-activity-status"></span><span id="current-activity-started"></span><span id="current-activity-running"></span></div><div id="recent-activity-list" class="max-h-[28rem] space-y-3 overflow-y-auto pr-1">@forelse($recentActivities as $activity)<div class="flex items-start justify-between gap-4 rounded-xl border border-slate-800 bg-slate-950/50 p-4"><div class="min-w-0"><p class="break-words text-[15px] font-medium leading-5 text-slate-200">{{ $activity['label'] }}</p><p class="mt-1.5 text-sm text-slate-500">{{ $activity['relative_time'] }}</p></div><x-admin.status-badge :status="$activity['status']" class="shrink-0" /></div>@empty<p class="rounded-xl border border-dashed border-slate-700 bg-slate-950/30 px-4 py-5 text-center text-base text-slate-500">No activity recorded.</p>@endforelse</div><span id="activity-live-indicator" class="hidden"></span><span id="last-tracker-check" class="hidden"></span><span id="last-momentum-scan" class="hidden"></span><span id="last-token-scan" class="hidden"></span></x-admin.panel>
    </div>

    <div id="tracker-status-badge" class="hidden"><span id="tracker-status-dot"></span><span id="tracker-status-text">{{ $systemStatus['status'] }}</span></div>
    <dialog id="close-position-modal" class="m-auto w-[calc(100%-2rem)] max-w-md rounded-2xl border border-slate-700 bg-slate-900 p-0 text-slate-100 backdrop:bg-slate-950/80"><form id="close-position-form" method="POST" class="space-y-5 p-6">@csrf<div><p class="text-xs font-bold uppercase tracking-wider text-red-300">Manual exit</p><h2 class="mt-2 text-xl font-semibold">Close <span id="modal-symbol"></span>?</h2></div><dl class="grid grid-cols-2 gap-3 rounded-xl bg-slate-950 p-4 text-sm"><div><dt class="text-slate-500">Return</dt><dd id="modal-return"></dd></div><div><dt class="text-slate-500">Remaining</dt><dd id="modal-remaining"></dd></div><div class="col-span-2"><dt class="text-slate-500">Estimated value</dt><dd id="modal-value"></dd></div></dl><p class="text-sm text-red-200">This closes 100% of the remaining paper position.</p><div class="flex justify-end gap-3"><button id="cancel-close" type="button" class="rounded-lg border border-slate-700 px-4 py-2">Cancel</button><button class="rounded-lg bg-red-500 px-4 py-2 font-semibold">Close Position</button></div></form></dialog>
</x-layouts.admin>
