packages:
  - "apps/*"
allowBuilds:
  cpu-features: false
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  ssh2: false
onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract
  - protobufjs
ignoredBuiltDependencies:
  - cpu-features
  - ssh2
