<x-dynamic-component :component="auth()->user()->is_admin ? 'layouts.admin' : 'layouts.app'" :title="($opportunity->symbol ?: 'Opportunity').' Opportunity'">
    <div class="flex flex-wrap items-center justify-between gap-4"><a href="{{ route('opportunities.index') }}" class="text-sm font-semibold text-slate-400 hover:text-white">← All Opportunities</a><x-opportunity-status :status="$opportunity->status" /></div>

    @if (session('success')) <div class="rounded-xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-sm text-emerald-200">{{ session('success') }}</div> @endif
    @if (session('warning')) <div class="rounded-xl border border-amber-400/20 bg-amber-400/10 px-4 py-3 text-sm text-amber-200">{{ session('warning') }}</div> @endif
    @if (session('error')) <div class="rounded-xl border border-red-400/20 bg-red-400/10 px-4 py-3 text-sm text-red-200">{{ session('error') }}</div> @endif

    <header class="rounded-3xl border border-slate-800 bg-slate-900/70 p-6 sm:p-8">
        <div class="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between">
            <div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><span class="rounded-full bg-violet-400/10 px-2.5 py-1 text-xs font-semibold uppercase text-violet-300">{{ $opportunity->chain->label() }}</span><span class="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">{{ str($opportunity->scanner)->replace('_', ' ')->title() }}</span><x-opportunity-status :status="$opportunity->status" /></div><h1 class="mt-4 text-4xl font-semibold text-white">{{ $opportunity->symbol ?: 'Unknown Token' }}</h1><p class="mt-1 text-slate-400">{{ $opportunity->name }}</p><div class="mt-4 flex max-w-2xl items-center gap-2 rounded-xl border border-slate-800 bg-slate-950/70 p-2 pl-3"><code class="min-w-0 flex-1 truncate text-xs text-slate-400" title="{{ $opportunity->address }}">{{ $opportunity->address }}</code><button type="button" data-copy-value="{{ $opportunity->address }}" class="copy-value shrink-0 rounded-lg border border-slate-700 px-3 py-1.5 text-xs font-semibold text-slate-300 hover:border-slate-500 hover:text-white">Copy</button></div></div>
            <div class="rounded-2xl border border-slate-700 bg-slate-950/70 p-5 lg:max-w-sm"><p class="text-xs font-semibold uppercase tracking-wider text-slate-500">Entry Policy at Qualification</p><p class="mt-2 text-lg font-semibold text-white">{{ str($opportunity->entry_mode->value)->replace('_', ' ')->title() }}</p><p class="mt-1 text-sm text-slate-400">Execution environment: {{ strtoupper($opportunity->execution_mode->value) }}</p></div>
        </div>
    </header>

    <section class="grid gap-px overflow-hidden rounded-2xl border border-slate-800 bg-slate-800 sm:grid-cols-2 lg:grid-cols-5">
        @foreach ([['Price', $opportunity->price !== null ? '$'.rtrim(rtrim(number_format((float) $opportunity->price, 12, '.', ''), '0'), '.') : 'N/A'], ['Market Cap', $opportunity->market_cap !== null ? '$'.number_format((float) $opportunity->market_cap, 2) : 'N/A'], ['Liquidity', $opportunity->liquidity !== null ? '$'.number_format((float) $opportunity->liquidity, 2) : 'N/A'], ['Volume', $opportunity->volume !== null ? '$'.number_format((float) $opportunity->volume, 2) : 'N/A'], ['Qualified', $opportunity->qualified_at?->format('M j, Y H:i:s') ?? 'N/A']] as [$label, $value])
            <div class="bg-slate-900 px-5 py-5"><p class="text-xs uppercase tracking-wider text-slate-600">{{ $label }}</p><p class="mt-2 font-semibold tabular-nums text-slate-200">{{ $value }}</p></div>
        @endforeach
    </section>

    @if ($opportunity->volume === null)
        <p class="-mt-5 text-xs text-slate-500">Volume was not captured by the scanner for this historical opportunity; no value has been inferred.</p>
    @endif

    @if ($opportunity->status === \App\Enums\TradeOpportunityStatus::PendingConfirmation)
        <section class="rounded-2xl border border-amber-400/25 bg-amber-400/5 p-6"><p class="text-xs font-bold uppercase tracking-[0.2em] text-amber-300">Decision Required</p><h2 class="mt-2 text-xl font-semibold text-white">Approve or ignore this opportunity</h2><p class="mt-2 text-sm text-slate-400">Approval revalidates the state and uses the currently configured execution environment. LIVE remains locked server-side.</p><div class="mt-5 flex flex-wrap gap-3"><form method="POST" action="{{ route('opportunities.approve', $opportunity) }}">@csrf<button class="rounded-xl bg-emerald-400 px-5 py-3 text-sm font-bold text-slate-950">Approve Opportunity</button></form><form method="POST" action="{{ route('opportunities.ignore', $opportunity) }}">@csrf<button class="rounded-xl border border-slate-600 px-5 py-3 text-sm font-semibold text-slate-200">Ignore</button></form></div></section>
    @elseif ($opportunity->status === \App\Enums\TradeOpportunityStatus::Qualified && $opportunity->entry_mode === \App\Enums\EntryMode::Signal)
        <section class="rounded-2xl border border-sky-400/20 bg-sky-400/5 p-5 text-sm text-sky-200"><strong>Signal only:</strong> this opportunity was recorded for visibility and will never execute automatically.</section>
    @endif

    @if ($opportunity->paperPosition)
        <section class="flex flex-col gap-5 rounded-2xl border border-emerald-400/25 bg-emerald-400/5 p-6 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-[0.2em] text-emerald-300">Paper Trade Opened</p><h2 class="mt-2 text-2xl font-semibold text-white">Position #{{ $opportunity->paperPosition->id }}</h2><div class="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-sm text-slate-400"><span>Execution mode: <strong class="text-slate-200">{{ $opportunity->execution_mode->value === 'paper' ? 'Paper' : 'Live' }}</strong></span><span>Entry policy: <strong class="text-slate-200">{{ str($opportunity->entry_mode->value)->title() }}</strong></span></div></div><a href="{{ $opportunity->paperPosition->status === 'open' ? route('dashboard').'#positions-heading' : route('trades.index') }}" class="rounded-xl bg-emerald-400 px-5 py-3 text-center text-sm font-bold text-slate-950">{{ $opportunity->paperPosition->status === 'open' ? 'View Position' : 'View Trade' }} →</a></section>
    @elseif ($opportunity->status === \App\Enums\TradeOpportunityStatus::Failed)
        <section class="rounded-2xl border border-red-400/25 bg-red-400/5 p-6"><p class="text-xs font-bold uppercase tracking-[0.2em] text-red-300">Execution Failed</p><p class="mt-2 text-sm text-slate-300">{{ $presentation['failure_reason'] ?? 'Execution could not be completed. No sensitive provider details are displayed.' }}</p></section>
    @endif

    <div class="grid gap-5 lg:grid-cols-2">
        <section class="rounded-2xl border border-slate-800 bg-slate-900/70 p-6"><p class="text-xs font-semibold uppercase tracking-[0.18em] text-sky-400">At Qualification</p><h2 class="mt-2 text-lg font-semibold text-white">Qualification Details</h2><dl class="mt-4 divide-y divide-slate-800">@forelse ($presentation['qualification'] as $field)<div class="flex justify-between gap-5 py-3 text-sm"><dt class="text-slate-500">{{ $field['label'] }}</dt><dd class="max-w-[60%] break-words text-right text-slate-300">{{ $field['value'] }}</dd></div>@empty<p class="py-4 text-sm text-slate-500">No additional qualification metadata was captured.</p>@endforelse</dl></section>
        <section class="rounded-2xl border border-slate-800 bg-slate-900/70 p-6"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-semibold uppercase tracking-[0.18em] text-amber-300">Chain-Aware Coverage</p><h2 class="mt-2 text-lg font-semibold text-white">Security Information</h2></div><span @class(['rounded-full px-2.5 py-1 text-[10px] font-bold uppercase', 'bg-emerald-400/10 text-emerald-300' => $presentation['security']['status'] === 'passed', 'bg-red-400/10 text-red-300' => $presentation['security']['status'] === 'failed', 'bg-slate-800 text-slate-400' => $presentation['security']['status'] === 'unavailable'])>{{ $presentation['security']['status'] }}</span></div><p class="mt-3 text-sm leading-6 text-slate-500">{{ $presentation['security']['summary'] }}</p><dl class="mt-4 divide-y divide-slate-800">@forelse ($presentation['security']['fields'] as $field)<div class="flex justify-between gap-5 py-3 text-sm"><dt class="text-slate-500">{{ $field['label'] }}</dt><dd class="max-w-[60%] break-words text-right text-slate-300">{{ $field['value'] }}</dd></div>@empty<p class="py-4 text-sm text-slate-500">Applicable security details were unavailable at qualification time.</p>@endforelse</dl></section>
    </div>

    <section class="rounded-2xl border border-slate-800 bg-slate-900/70 p-6"><h2 class="text-lg font-semibold text-white">Decision Audit</h2><div class="mt-4 divide-y divide-slate-800">@forelse ($opportunity->events->sortByDesc('id') as $event)<div class="flex flex-wrap justify-between gap-3 py-3 text-sm"><span class="font-semibold text-slate-300">{{ str($event->action)->replace('_', ' ')->title() }}</span><span class="text-slate-500">{{ $event->from_status }} → {{ $event->to_status }} · {{ $event->user?->name ?? 'System' }} · {{ $event->created_at->diffForHumans() }}</span></div>@empty<p class="py-4 text-sm text-slate-500">No manual actions recorded.</p>@endforelse</div></section>
</x-dynamic-component>
