<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    @php $applicationName = app(\App\Services\ApplicationSettingsService::class)->get('general.application_name'); @endphp
    <head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>{{ isset($title) ? $title.' · '.$applicationName : $applicationName }}</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
    <body class="min-h-screen bg-[#07101d] font-sans text-slate-100 antialiased">
        <div class="min-h-screen lg:grid lg:grid-cols-[284px_minmax(0,1fr)]">
            <div id="admin-sidebar-backdrop" class="fixed inset-0 z-40 hidden bg-slate-950/80 backdrop-blur-sm lg:hidden"></div>
            <aside id="admin-sidebar" class="fixed inset-y-0 left-0 z-50 flex w-[284px] -translate-x-full flex-col border-r border-slate-700/70 bg-gradient-to-b from-[#0a1727] to-[#07111e] shadow-2xl transition-transform duration-200 lg:sticky lg:top-0 lg:h-screen lg:translate-x-0 lg:shadow-none">
                <div class="flex h-24 items-center gap-3.5 border-b border-slate-800/90 px-5"><div class="flex size-12 shrink-0 items-center justify-center rounded-2xl border border-blue-300/20 bg-gradient-to-br from-blue-500 to-violet-600 text-xl shadow-lg shadow-blue-950/40">◆</div><div class="min-w-0"><p class="truncate text-lg font-bold tracking-tight text-white">{{ $applicationName }}</p><p class="mt-0.5 text-sm text-slate-500">Administration</p></div><span class="ml-auto rounded-full border border-violet-400/25 bg-violet-400/10 px-2.5 py-1 text-[11px] font-bold text-violet-300">ADMIN</span></div>
                @php $linkClass = 'group flex items-center gap-3.5 rounded-xl px-3.5 py-3 text-[15px] font-medium transition'; $activeClass = 'bg-gradient-to-r from-blue-500/20 to-blue-500/10 text-blue-100 ring-1 ring-inset ring-blue-400/25 shadow-sm'; $idleClass = 'text-slate-400 hover:bg-slate-800/75 hover:text-white'; @endphp
                <nav class="flex-1 space-y-7 overflow-y-auto px-4 py-6" aria-label="Administrator navigation">
                    <div><p class="px-3.5 text-[11px] font-bold uppercase tracking-[0.2em] text-slate-500">Overview</p><div class="mt-2.5"><a href="{{ route('dashboard') }}" class="{{ $linkClass }} {{ request()->routeIs('dashboard') ? $activeClass : $idleClass }}"><span class="w-5 text-center text-lg text-blue-400">▦</span>Dashboard</a></div></div>
                    <div><p class="px-3.5 text-[11px] font-bold uppercase tracking-[0.2em] text-slate-500">Trading</p><div class="mt-2.5 space-y-1"><a href="{{ route('opportunities.index') }}" class="{{ $linkClass }} {{ request()->routeIs('opportunities.*') ? $activeClass : $idleClass }}"><span class="w-5 text-center text-lg">◇</span>Opportunities</a><a href="{{ route('dashboard') }}#positions" class="{{ $linkClass }} {{ $idleClass }}"><span class="w-5 text-center text-lg">◎</span>Open Positions</a><a href="{{ route('trades.index') }}" class="{{ $linkClass }} {{ request()->routeIs('trades.*') ? $activeClass : $idleClass }}"><span class="w-5 text-center text-lg">▤</span>Trade History</a><a href="{{ route('dashboard') }}#wallets" class="{{ $linkClass }} {{ $idleClass }}"><span class="w-5 text-center text-lg">▣</span>Paper Wallets</a></div></div>
                    <div><p class="px-3.5 text-[11px] font-bold uppercase tracking-[0.2em] text-slate-500">Operations</p><div class="mt-2.5 space-y-1"><a href="{{ route('dashboard') }}#scanner-controls" class="{{ $linkClass }} {{ $idleClass }}"><span class="w-5 text-center text-lg">⌁</span>Scanner Control</a><a href="{{ route('dashboard') }}#system-status" class="{{ $linkClass }} {{ $idleClass }}"><span class="w-5 text-center text-lg">◉</span>Tracker & Queue</a><a href="{{ route('dashboard') }}#system-activity" class="{{ $linkClass }} {{ $idleClass }}"><span class="w-5 text-center text-lg">↻</span>System Activity</a></div></div>
                    <div><p class="px-3.5 text-[11px] font-bold uppercase tracking-[0.2em] text-slate-500">Configuration</p><div class="mt-2.5 space-y-1"><a href="{{ route('settings.index') }}" class="{{ $linkClass }} {{ request()->routeIs('settings.*') ? $activeClass : $idleClass }}"><span class="w-5 text-center text-lg">⚙</span>Platform Settings</a><a href="{{ route('telegram.settings') }}" class="{{ $linkClass }} {{ request()->routeIs('telegram.*') ? $activeClass : $idleClass }}"><span class="w-5 text-center text-lg">△</span>Telegram Bot</a></div></div>
                </nav>
                <div class="border-t border-slate-800/90 p-4"><a href="{{ route('account.edit') }}" class="flex items-center gap-3.5 rounded-2xl border border-slate-800 bg-slate-900/75 p-3.5 transition hover:border-slate-700 hover:bg-slate-800"><span class="flex size-11 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-blue-400 to-violet-500 text-base font-bold text-white shadow-md">{{ mb_strtoupper(mb_substr(auth()->user()->name, 0, 1)) }}</span><span class="min-w-0"><span class="block truncate text-[15px] font-semibold text-white">{{ auth()->user()->name }}</span><span class="mt-0.5 block text-sm text-slate-500">System Administrator</span></span></a></div>
            </aside>
            <div class="min-w-0"><header class="sticky top-0 z-30 flex h-20 items-center gap-4 border-b border-slate-700/70 bg-[#091421]/90 px-4 shadow-lg shadow-black/10 backdrop-blur-xl sm:px-6 lg:px-8"><button id="admin-sidebar-toggle" type="button" class="flex size-11 items-center justify-center rounded-xl border border-slate-700 bg-slate-900 text-lg text-slate-300 lg:hidden" aria-controls="admin-sidebar" aria-expanded="false"><span class="sr-only">Open navigation</span>☰</button><div class="min-w-0"><p class="truncate text-base font-semibold text-white">{{ $title ?? 'Administration' }}</p><p class="hidden text-sm text-slate-500 sm:block">Monitor, manage, and operate the platform</p></div><div class="ml-auto flex items-center gap-3 sm:gap-4"><span class="hidden size-10 items-center justify-center rounded-full bg-gradient-to-br from-blue-400 to-violet-500 font-bold text-white shadow-md sm:flex">{{ mb_strtoupper(mb_substr(auth()->user()->name, 0, 1)) }}</span><a href="{{ route('account.edit') }}" class="hidden text-right md:block"><span class="block text-[15px] font-semibold text-white">{{ auth()->user()->name }}</span><span class="block text-sm text-slate-500">Administrator</span></a><form method="POST" action="{{ route('logout') }}">@csrf<button class="rounded-xl border border-slate-700 bg-slate-900/70 px-3.5 py-2.5 text-sm font-semibold text-slate-300 transition hover:border-slate-600 hover:bg-slate-800 hover:text-white">Sign Out</button></form></div></header><main class="flex w-full flex-col gap-6 px-4 py-6 sm:px-6 lg:px-8 xl:px-10 2xl:px-12 lg:py-8">{{ $slot }}</main></div>
        </div>
    </body>
</html>
