<x-layouts.app title="Platform Settings">
    @php
        $item = fn (string $key) => $settings->flatten(1)->firstWhere('key', $key);
        $executionMode = old('execution_mode', $item('trading.execution_mode')['value']);
        $entryMode = old('entry_mode', $item('trading.entry_mode')['value']);
    @endphp

    <header class="flex flex-col gap-4 border-b border-slate-800 pb-7 lg:flex-row lg:items-end lg:justify-between">
        <div><p class="text-xs font-semibold uppercase tracking-[0.22em] text-emerald-400">Administration</p><h1 class="mt-2 text-3xl font-semibold text-white">Platform Settings</h1><p class="mt-2 text-sm text-slate-400">Control how qualified opportunities move through the trading platform.</p></div>
        <div class="flex gap-2"><span class="rounded-full bg-sky-400/10 px-3 py-2 text-xs font-semibold text-sky-300">{{ strtoupper($executionMode) }}</span><span class="rounded-full bg-violet-400/10 px-3 py-2 text-xs font-semibold text-violet-300">{{ strtoupper($entryMode) }}</span></div>
    </header>

    @if (session('success')) <div class="rounded-xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-sm text-emerald-200">{{ session('success') }}</div> @endif
    @if (session('warning')) <div class="rounded-xl border border-amber-400/20 bg-amber-400/10 px-4 py-3 text-sm text-amber-200">{{ session('warning') }}</div> @endif
    @if (session('error')) <div class="rounded-xl border border-red-400/20 bg-red-400/10 px-4 py-3 text-sm text-red-200">{{ session('error') }}</div> @endif
    @if ($errors->any()) <div class="rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div> @endif

    <form method="POST" action="{{ route('settings.update') }}" class="space-y-6">
        @csrf @method('PUT')

        <section class="rounded-3xl border border-emerald-400/20 bg-gradient-to-br from-slate-900 to-slate-900/60 p-6 sm:p-8">
            <p class="text-xs font-bold uppercase tracking-[0.22em] text-emerald-400">Trading Mode</p><h2 class="mt-2 text-2xl font-semibold text-white">Choose the execution environment</h2>
            <div class="mt-6 grid gap-4 md:grid-cols-2">
                @foreach ([['paper', 'PAPER', 'Safe sandbox using simulated funds.', 'emerald'], ['live', 'LIVE', 'Real-money execution environment. Currently locked/not enabled.', 'red']] as [$value, $label, $description, $tone])
                    <label class="relative cursor-pointer"><input class="peer sr-only" type="radio" name="execution_mode" value="{{ $value }}" @checked($executionMode === $value)><span @class(['block h-full rounded-2xl border border-slate-700 bg-slate-950/60 p-5 transition', 'peer-checked:border-emerald-400 peer-checked:bg-emerald-400/10' => $tone === 'emerald', 'peer-checked:border-red-400 peer-checked:bg-red-400/10' => $tone === 'red'])><strong class="text-lg text-white">{{ $label }}</strong><span class="mt-2 block text-sm leading-6 text-slate-400">{{ $description }}</span></span></label>
                @endforeach
            </div>
            <div id="live-execution-warning" class="mt-5 rounded-2xl border border-red-400/30 bg-red-400/10 p-5 text-red-100 {{ $executionMode === 'live' ? '' : 'hidden' }}"><p class="font-bold">LIVE EXECUTION LOCKED</p><p class="mt-1 text-sm">Live trading architecture is configured, but real-money execution is not enabled yet.</p><p id="live-auto-warning" class="mt-2 text-sm font-semibold text-amber-200 {{ $entryMode === 'auto' ? '' : 'hidden' }}">Automatic real-money trading will require explicit activation after wallet and risk implementation.</p></div>
        </section>

        <section class="rounded-3xl border border-violet-400/20 bg-slate-900/70 p-6 sm:p-8"><p class="text-xs font-bold uppercase tracking-[0.22em] text-violet-400">Entry Behavior</p><h2 class="mt-2 text-2xl font-semibold text-white">What happens after qualification?</h2><div class="mt-6 grid gap-4 lg:grid-cols-3">
            @foreach ([['signal', 'SIGNAL ONLY', 'Find and notify about qualified opportunities. Never automatically enter.'], ['confirm', 'CONFIRM BEFORE BUY', 'Wait for explicit approval before using the execution pipeline.'], ['auto', 'AUTO BUY', 'Automatically enter according to active strategy and safety configuration.']] as [$value, $label, $description])
                <label class="cursor-pointer"><input class="peer sr-only" type="radio" name="entry_mode" value="{{ $value }}" @checked($entryMode === $value)><span class="block h-full rounded-2xl border border-slate-700 bg-slate-950/60 p-5 transition peer-checked:border-violet-400 peer-checked:bg-violet-400/10"><strong class="text-sm text-white">{{ $label }}</strong><span class="mt-2 block text-sm leading-6 text-slate-400">{{ $description }}</span></span></label>
            @endforeach
        </div></section>

        <section class="grid gap-5 lg:grid-cols-[1.35fr_1fr]">
            <div class="rounded-3xl border border-amber-400/20 bg-slate-900/70 p-6"><p class="text-xs font-bold uppercase tracking-[0.22em] text-amber-300">Active Strategy</p><h2 class="mt-2 text-xl font-semibold">Paper position protection</h2><p class="mt-1 text-xs text-slate-500">New positions snapshot these values. Existing positions remain unchanged.</p><div class="mt-5 grid gap-4 sm:grid-cols-3"><x-settings.input name="stop_loss_percent" label="Stop Loss %" type="number" step="0.01" :value="$strategy['stop_loss_percent']" /><x-settings.input name="protection_level_1_percent" label="Protection 1 %" type="number" step="0.01" :value="$strategy['protection_level_1_percent']" /><x-settings.input name="protection_level_2_percent" label="Protection 2 %" type="number" step="0.01" :value="$strategy['protection_level_2_percent']" /></div></div>
            <div class="rounded-3xl border border-slate-800 bg-slate-900/70 p-6"><p class="text-xs font-bold uppercase tracking-[0.22em] text-slate-500">General & Scanner</p><div class="mt-5 grid gap-4"><x-settings.input name="application_name" label="Application Name" :value="$item('general.application_name')['value']" /><x-settings.input name="max_chase_percent" label="Maximum Chase %" type="number" step="0.01" :value="$item('scanner.max_chase_percent')['value']" /><x-settings.input name="tracker_snapshot_seconds" label="Snapshot Interval (seconds)" type="number" :value="$item('tracker.snapshot_seconds')['value']" /></div></div>
        </section>

        <section class="rounded-3xl border border-slate-800 bg-slate-900/70 p-6"><div class="flex flex-wrap items-end justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-[0.22em] text-sky-400">Integration Status</p><h2 class="mt-2 text-xl font-semibold">Configured services and live heartbeat</h2></div><p class="text-xs text-slate-500">Configured ≠ connected. Use tests to verify providers.</p></div><div class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">@foreach($integrations as $integration)<div class="rounded-2xl border border-slate-800 bg-slate-950/60 p-4"><div class="flex items-center justify-between gap-2"><strong class="text-sm text-white">{{ $integration['label'] }}</strong><span class="rounded-full px-2 py-1 text-[10px] font-bold uppercase {{ in_array($integration['status'], ['active', 'configured']) ? 'bg-emerald-400/10 text-emerald-300' : ($integration['status'] === 'stale' ? 'bg-amber-400/10 text-amber-300' : 'bg-slate-800 text-slate-400') }}">{{ str($integration['status'])->replace('_', ' ') }}</span></div><p class="mt-3 text-xs leading-5 text-slate-500">{{ $integration['detail'] }}</p></div>@endforeach</div></section>

        <section class="grid gap-5 lg:grid-cols-2">
            <div class="rounded-2xl border border-slate-800 bg-slate-900/70 p-6"><h2 class="text-lg font-semibold">Platform Telegram Notifications</h2><div class="mt-5 grid gap-4"><label class="flex items-center gap-3 text-sm"><input type="checkbox" name="telegram_enabled" value="1" @checked($item('telegram.enabled')['value'])> Enable legacy platform notifications</label><x-settings.secret name="telegram_bot_token" label="Bot Token" :masked="$item('telegram.bot_token')['masked']" /><x-settings.secret name="telegram_chat_id" label="Notification Destination" :masked="$item('telegram.chat_id')['masked']" /><x-settings.input name="telegram_bot_username" label="Bot Username" :value="$item('telegram.bot_username')['value']" /><x-settings.secret name="telegram_webhook_secret" label="Webhook Secret" :masked="$item('telegram.webhook_secret')['masked']" /><button type="submit" form="test-telegram" class="rounded-xl border border-slate-700 px-4 py-2 text-sm font-semibold">Test Telegram</button><a href="{{ route('telegram.settings') }}" class="rounded-xl border border-sky-400/30 px-4 py-2 text-center text-sm font-semibold text-sky-300">Manage My Interactive Bot</a></div></div>
            <div class="rounded-2xl border border-slate-800 bg-slate-900/70 p-6"><h2 class="text-lg font-semibold">Providers & Blockchain</h2><div class="mt-5 grid gap-4"><x-settings.secret name="birdeye_api_key" label="Birdeye API Key" :masked="$item('market_data.birdeye_api_key')['masked']" /><x-settings.secret name="solana_rpc_url" label="Solana RPC URL" :masked="$item('blockchain.solana_rpc_url')['masked']" /><div class="grid grid-cols-3 gap-2"><button type="submit" form="test-solana" class="rounded-lg border border-slate-700 px-2 py-2 text-xs">Test Solana</button><button type="submit" form="test-ethereum" class="rounded-lg border border-slate-700 px-2 py-2 text-xs">Test Ethereum</button><button type="submit" form="test-market-data" class="rounded-lg border border-slate-700 px-2 py-2 text-xs">Test Market Data</button></div></div></div>
        </section>

        <section class="rounded-3xl border border-red-400/20 bg-slate-900/70 p-6"><p class="text-xs font-bold uppercase tracking-[0.22em] text-red-300">Risk / Safety</p><div class="mt-5 rounded-2xl border border-red-400/20 bg-red-400/5 p-4"><p class="text-xs font-bold uppercase text-red-300">Active Now</p><label class="mt-3 flex items-center gap-3 text-sm font-semibold"><input type="checkbox" name="kill_switch" value="1" @checked($item('risk.kill_switch')['value'])> Emergency Trading Kill Switch</label><p class="mt-2 text-xs text-slate-500">Blocks new executions while monitoring and exits continue.</p></div><div class="mt-6"><p class="text-xs font-bold uppercase text-slate-500">Live Risk Controls — Foundation Only</p><p class="mt-1 text-xs text-slate-500">Stored for the disabled live layer; these limits do not change current paper behavior.</p><div class="mt-4 grid gap-4 md:grid-cols-3"><x-settings.input name="max_trade_amount" label="Maximum Trade Amount" type="number" step="0.0001" :value="$item('risk.max_trade_amount')['value']" /><x-settings.input name="max_open_positions" label="Maximum Open Positions" type="number" :value="$item('risk.max_open_positions')['value']" /><x-settings.input name="max_daily_loss" label="Maximum Daily Loss" type="number" step="0.01" :value="$item('risk.max_daily_loss')['value']" /><x-settings.input name="max_slippage_percent" label="Maximum Slippage %" type="number" step="0.01" :value="$item('risk.max_slippage_percent')['value']" /><x-settings.input name="minimum_wallet_reserve" label="Minimum Wallet Reserve" type="number" step="0.0001" :value="$item('risk.minimum_wallet_reserve')['value']" /><x-settings.input name="trade_cooldown_seconds" label="Trade Cooldown (seconds)" type="number" :value="$item('risk.trade_cooldown_seconds')['value']" /></div></div></section>

        <div class="sticky bottom-4 flex justify-end"><button class="rounded-xl bg-emerald-400 px-6 py-3 font-semibold text-slate-950 shadow-xl shadow-black/30 hover:bg-emerald-300">Save Platform Settings</button></div>
    </form>

    @foreach(['telegram','solana','ethereum','market-data'] as $integration)<form id="test-{{ $integration }}" method="POST" action="{{ route('settings.test', $integration) }}">@csrf</form>@endforeach
    <section class="rounded-2xl border border-slate-800 bg-slate-900/70 p-6"><h2 class="text-lg font-semibold">Recent Configuration Audit</h2><div class="mt-4 space-y-2">@forelse($audits as $audit)<div class="flex justify-between gap-4 border-t border-slate-800 py-3 text-sm"><span>{{ $audit->setting_key }}</span><span class="text-slate-500">{{ $audit->action }} · {{ $audit->created_at->diffForHumans() }}</span></div>@empty<p class="text-sm text-slate-500">No settings changes recorded.</p>@endforelse</div></section>
</x-layouts.app>
